[package]
name = "zero2prod"
version = "0.1.0"
authors = ["David Weis <dweis7@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "app"

[dependencies]
actix-web = "3.2"
actix-rt = "1.1"
serde = { version = "1", features = ["derive"]}
sqlx = { version = "0.4.1", default-features = false, features = ["runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate"] }
config = "0.10"
uuid = { version = "0.8", features = ["v4"] }
chrono = "0.4"

[dev-dependencies]
reqwest = "0.10"
tokio = "0.2"
