[package]
name = "zero2prod"
version = "0.1.0"
authors = ["David Weis <dweis7@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "app"

[dependencies]
actix-web = "3.2"
actix-rt = "1.1"
