[package]
name = "zero2prod"
version = "0.1.0"
authors = ["David Weis <dweis7@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "app"

[dependencies]
actix-web = "3.2"
actix-rt = "1.1"
tokio = "0.2"
serde = { version = "1", features = ["derive"]}
sqlx = { version = "0.4.1", default-features = false, features = ["runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate"] }
config = "0.10"
uuid = { version = "0.8", features = ["v4"] }
chrono = "0.4"
tracing = "0.1"
actix-files = "0.4"
tracing-futures = '0.2'
tracing-subscriber = { version = "0.2.12", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.1"
tracing-log = "0.1"
tracing-actix-web = "0.2"

[dev-dependencies]
reqwest = { version = "0.10", features = ["json"] }
lazy_static = "1.4"
